networks:
  proxy_net:
    external: true
    name: nginx_proxy_net

services:
  app:
    container_name: somo-convalidaciones
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    volumes:
      - ./backend/scripts/db.sqlite:/app/backend/scripts/db.sqlite
    networks:
      - proxy_net
