"""Load FP catalog (grados/familias/ciclos/modulos) from JSON into SQLite."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
from typing import Any


BACKEND_ROOT = Path(__file__).resolve().parents[1]
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

from app.db.database import (  # noqa: E402
    DBConfig,
    clear_catalog,
    connect,
    find_catalog_entity_by_nombre,
    get_or_create_catalog_entity,
    init_db,
)


# Define y procesa los argumentos de linea de comandos.
def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Load catalog JSON into sqlite.")
    parser.add_argument("--db", default="data/somo.db", help="Path to SQLite DB")
    parser.add_argument(
        "--json",
        default="fp_grados.json",
        help="Path to source JSON generated by scrapers/build_fp_data.py",
    )
    parser.add_argument(
        "--truncate",
        action="store_true",
        help="Delete existing catalog before loading (DELETE FROM grados with CASCADE).",
    )
    return parser.parse_args()


# Extrae un nombre valido desde texto o diccionario de entrada.
def _extract_name(item: Any, *keys: str) -> str | None:
    if isinstance(item, str):
        value = item.strip()
        return value or None
    if isinstance(item, dict):
        for key in keys:
            value = item.get(key)
            if isinstance(value, str) and value.strip():
                return value.strip()
    return None


# Carga el catalogo FP desde JSON hacia la base de datos.
def load_catalog(db_path: Path, json_path: Path, truncate: bool = False) -> dict[str, int]:
    if not json_path.exists():
        raise FileNotFoundError(f"Catalog JSON not found: {json_path}")

    init_db(DBConfig(path=db_path))
    data = json.loads(json_path.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise ValueError("Catalog JSON must be a list of grados.")

    conn = connect(DBConfig(path=db_path))
    counters = {"grados": 0, "familias": 0, "ciclos": 0, "modulos": 0}
    try:
        if truncate:
            clear_catalog(conn)

        for grado_data in data:
            grado_nombre = _extract_name(grado_data, "grado", "nombre")
            if not grado_nombre:
                continue
            grado_id_before = find_catalog_entity_by_nombre(
                conn,
                "grado",
                grado_nombre,
            )
            grado_id = get_or_create_catalog_entity(
                conn,
                "grado",
                grado_nombre,
            )
            if grado_id_before is None:
                counters["grados"] += 1

            familias = grado_data.get("familias", []) if isinstance(grado_data, dict) else []
            if not isinstance(familias, list):
                continue
            for familia_data in familias:
                familia_nombre = _extract_name(familia_data, "familia", "nombre")
                if not familia_nombre:
                    continue
                familia_before = find_catalog_entity_by_nombre(
                    conn,
                    "familia",
                    familia_nombre,
                    parent_id=grado_id,
                )
                familia_id = get_or_create_catalog_entity(
                    conn,
                    "familia",
                    familia_nombre,
                    parent_id=grado_id,
                )
                if familia_before is None:
                    counters["familias"] += 1

                ciclos = familia_data.get("ciclos", []) if isinstance(familia_data, dict) else []
                if not isinstance(ciclos, list):
                    continue
                for ciclo_data in ciclos:
                    ciclo_nombre = _extract_name(ciclo_data, "ciclo", "nombre")
                    if not ciclo_nombre:
                        continue
                    titulo = ciclo_data.get("titulo") if isinstance(ciclo_data, dict) else None
                    id_oficial = ciclo_data.get("id_oficial") if isinstance(ciclo_data, dict) else None
                    normativa = ciclo_data.get("normativa") if isinstance(ciclo_data, dict) else None

                    ciclo_before = find_catalog_entity_by_nombre(
                        conn,
                        "ciclo",
                        ciclo_nombre,
                        parent_id=familia_id,
                    )
                    ciclo_id = get_or_create_catalog_entity(
                        conn,
                        "ciclo",
                        ciclo_nombre,
                        parent_id=familia_id,
                        titulo=titulo,
                        id_oficial=id_oficial,
                        normativa=normativa,
                    )
                    if ciclo_before is None:
                        counters["ciclos"] += 1

                    modulos = ciclo_data.get("modulos", []) if isinstance(ciclo_data, dict) else []
                    if not isinstance(modulos, list):
                        continue
                    for modulo_data in modulos:
                        modulo_nombre = _extract_name(modulo_data, "nombre", "modulo")
                        if not modulo_nombre:
                            continue
                        modulo_id_oficial = (
                            modulo_data.get("id_oficial") if isinstance(modulo_data, dict) else None
                        )
                        modulo_before = find_catalog_entity_by_nombre(
                            conn,
                            "modulo",
                            modulo_nombre,
                            parent_id=ciclo_id,
                        )
                        get_or_create_catalog_entity(
                            conn,
                            "modulo",
                            modulo_nombre,
                            parent_id=ciclo_id,
                            id_oficial=modulo_id_oficial,
                        )
                        if modulo_before is None:
                            counters["modulos"] += 1
    finally:
        conn.close()
    return counters


# Punto de entrada principal del script.
def main() -> None:
    args = parse_args()
    stats = load_catalog(
        db_path=Path(args.db),
        json_path=Path(args.json),
        truncate=bool(args.truncate),
    )
    print("Catalog load completed.")
    print(
        "Inserted -> "
        f"grados: {stats['grados']}, "
        f"familias: {stats['familias']}, "
        f"ciclos: {stats['ciclos']}, "
        f"modulos: {stats['modulos']}"
    )


if __name__ == "__main__":
    main()
